// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import FinalMapController from "./final_map_controller"
application.register("final-map", FinalMapController)

import GreetController from "./greet_controller"
application.register("greet", GreetController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import RouteController from "./route_controller"
application.register("route", RouteController)
