meta_product_name: "Veloo"
meta_title: "Veloo - La tête dans le guidon en toute sécurité!"
meta_description: "Veloo est un véritable assistant de navigation destiné aux cyclistes urbains et péri-urbains. Il est simple, participatif et open-source."
meta_image: "logo.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
